menu:
- {name: 'About', url: '/about'}
- {name: 'Research', url: '/research'}
- {name: 'Resources', url: '/Resources'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/evazlimen'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/eva-zlimen-7b54a5285/', name: 'LinkedIn', handle: 'eva-zlimen-7b54a5285'}
- {icon: 'orcid', link: 'https://orcid.org/0009-0006-9842-147X', name: 'ORCID', handle: '0009-0006-9842-147X'}

contacts:
- {name: 'Eva Zlimen', title: 'Graduate Student', department: 'Earth, Planetary, and Space Sciences', institution: 'University of California, Los Angeles', institution_address: 'Los Angeles, California 90095', email: 'ezlimen@g.ucla.edu', office: 'Geology 4642', image: 'assets/img/contact.jpg'}
